// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmgBNvre3AikmqnaS583PJc0FCPOOUFsg',
    appId: '1:367681497587:web:32749285cbd60bd9c20a86',
    messagingSenderId: '367681497587',
    projectId: 'mus3if--app',
    authDomain: 'mus3if--app.firebaseapp.com',
    storageBucket: 'mus3if--app.firebasestorage.app',
    measurementId: 'G-ZV51NDZ475',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKcTjZXuRMF22hQJVJNHqbgAJ5fr5QUmw',
    appId: '1:367681497587:android:aeaad17d72fc6affc20a86',
    messagingSenderId: '367681497587',
    projectId: 'mus3if--app',
    storageBucket: 'mus3if--app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG_ziEJUktpCRKUB79I9R-ORebYMoDcJ0',
    appId: '1:367681497587:ios:a55df76ba252a9c4c20a86',
    messagingSenderId: '367681497587',
    projectId: 'mus3if--app',
    storageBucket: 'mus3if--app.firebasestorage.app',
    androidClientId: '367681497587-jfdhcraifva1fju2397fu2f3kmf9lrcd.apps.googleusercontent.com',
    iosClientId: '367681497587-g4rn5nals56kkb6smm5bdm1iknpre1ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.mus3if',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG_ziEJUktpCRKUB79I9R-ORebYMoDcJ0',
    appId: '1:367681497587:ios:a55df76ba252a9c4c20a86',
    messagingSenderId: '367681497587',
    projectId: 'mus3if--app',
    storageBucket: 'mus3if--app.firebasestorage.app',
    androidClientId: '367681497587-jfdhcraifva1fju2397fu2f3kmf9lrcd.apps.googleusercontent.com',
    iosClientId: '367681497587-g4rn5nals56kkb6smm5bdm1iknpre1ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.mus3if',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmgBNvre3AikmqnaS583PJc0FCPOOUFsg',
    appId: '1:367681497587:web:f0c6e59cb4204cd2c20a86',
    messagingSenderId: '367681497587',
    projectId: 'mus3if--app',
    authDomain: 'mus3if--app.firebaseapp.com',
    storageBucket: 'mus3if--app.firebasestorage.app',
    measurementId: 'G-MZSCHSLG3R',
  );
}
